name: aetherium_movil
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_riverpod: ^3.0.0-dev.15
  riverpod_annotation: ^3.0.0-dev.15
  google_fonts: ^6.2.1
  shared_preferences: ^2.5.3
  flutter_quill: ^11.4.1
  uuid: ^4.5.1
  flutter_quill_extensions: ^11.0.0
  path: ^1.9.1
  flutter_localizations:
    sdk: flutter
  intl: any
  freezed_annotation: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_lint: ^3.0.0-dev.15
  riverpod_generator: ^3.0.0-dev.15
  build_runner: ^2.4.15
  custom_lint: ^0.7.5

flutter:
  uses-material-design: true
